Fix resolv.conf reset on machine restart
zanaca/docker-dns pull request #35
Opened 2021-07-26 20:32 UTC by alexandre-slp

After Ubuntu version 18, [Netplan](https://netplan.io/) started being responsible for managing the network configurations and the `/etc/resolv.conf` started being overwritten every time the machine restarted resulting in missing the docker-dns container ip from the nameservers list.

To solve this problem the package `resolvconf` must be installed (new dependency) and the docker-dns container ip must be saved in the correct files: `/etc/resolvconf/resolv.conf.d/head` and `/etc/resolvconf/resolv.conf.d/tail`

2021-08-09 13:03 UTC, zanaca requested changes

2021-08-09 13:03 UTC, zanaca commented on src/install.py
> +            subprocess.run(['sudo', 'resolvconf', '-u'])
Please do not use any shell process

2021-08-09 20:43 UTC, alexandre-slp commented on src/install.py
> +            subprocess.run(['sudo', 'resolvconf', '-u'])
I am afraid there is no other way =/

2021-08-10 22:55 UTC, alexandre-slp reviewed
Is it ok now?

2021-08-10 22:55 UTC, alexandre-slp commented on src/install.py
> +            subprocess.run(['resolvconf', '-u'])
Removed `sudo`, is it ok now?
(still working)

2021-08-10 22:55 UTC, alexandre-slp commented on src/uninstall.py
> +        subprocess.run(['resolvconf', '-u'])
removed `sudo` from here too.

2021-08-10 22:58 UTC, alexandre-slp commented on src/install.py
> +            subprocess.run(['resolvconf', '-u'])
The best approach I have found is using `resolvconf`... Couldn't find anything better and scalable for the end user.

2022-02-23 15:41 UTC, merged